### ISSUE TITLE
404 Not Found on public

### ISSUE THREAD

**Issue by dwadp** [dalikewara/janggelan#1]
When i create a fresh project with janggelan, and i started a php built in server pointed to the janggelan's public folder on my app, i always get a 404 not found error, although I haven't yet touch the request.php file.

**Comment by dalikewara** [comment]
Hello, thank you for stopping by at this repository. BTW, if you can speak in Indonesian, I will very glad, because I am not good in English ^_^.

I think that's because there is no request cache directory in backend system. It lost when I pushed an empty directory. I just make a new commit that maybe can solve your problem.

**Comment by dwadp** [comment]
Ok, makasih banyak mas @dalikewara , tapi maaf sebelumnya, :). Saya akan coba dulu.

**Comment by dalikewara** [comment]
Okeh... Terima kasih @dewaadiperdana  sudah mencoba Janggelan. Saya berharap kamu sering menemukan issue, supaya bisa saya perbaiki, dan framework ini bisa lebih solid lagi.

Harusnya emang lebih keren pakek bahasa Inggris ya, cuman saya perlu banyak belajar lagi, hehehe...

**Comment by dwadp** [comment]
Nggak apa2 @dalikewara , sebenarnya saya suka kode dibalik janggelan framework ini, framework ini memberikan saya banyak inspirasi. Semangat terus mengembangkan framework janggelan @dalikewara.

**Comment by dalikewara** [comment]
Terima kasih. Oh iya, sebagai informasi, saya rencana mau nyusun struktur baru untuk Janggelan. Nanti framework ini bakal lebih micro, lebih banyak mengarah ke Web Service/API, dan nanti untuk MVC juga saya permudah penggunaannya.

**Comment by dwadp** [comment]
Pasti saya tunggu @dalikewara.

**Comment by dwadp** [comment]
Masih nggak mau @dalikewara , ini tampilan cmd nya

C:\MAMP\htdocs\janggelan-master>php -S localhost:8000
PHP 7.0.9 Development Server started at Sat Feb  4 12:42:36 2017
Listening on http://localhost:8000
Document root is C:\MAMP\htdocs\janggelan-master
Press Ctrl-C to quit.
[Sat Feb  4 12:48:29 2017] ::1:61295 [404]: / - No such file or directory
[Sat Feb  4 12:48:29 2017] ::1:61296 [404]: /favicon.ico - No such file or directory
[Sat Feb  4 12:50:35 2017] ::1:61309 [404]: / - No such file or directory

Harusnya kan dia bukan membaca '/' direktori.

**Comment by dalikewara** [comment]
Itu sudah masuk ke folder public? Pada directory mu mungkin kayak gini: C:\MAMP\htdocs\janggelan-master/public.

Itu document root nya di Document root is C:\MAMP\htdocs\janggelan-master, bukan di Document root is C:\MAMP\htdocs\janggelan-master/public

Bisa lihat list dari directory janggelan-master?

**Comment by dwadp** [comment]
Ohh, udah2, saya salah ternyata. Sorry @dalikewara, saya ngerepotin :)

**Comment by dalikewara** [comment]
Nggak papa, saya malah seneng dapet feedback... Kalau lagi nggak sibuk saya pasti dengan senang membantu.
